site_name: TUSat Docs
docs_dir: tusat-docs
nav:
  - Home: index.md
  - EPS: eps/eps.md
  - OBC + Commu: obc-commu/obc-commu.md
  - ADCS : adcs/adcs.md
  - Documents: document.md
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
plugins:
  - glightbox
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 # Icon for light mode
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4 # Icon for dark mode
        name: Switch to light mode