site_name: TUSat Docs
docs_dir: eps-docs
nav:
  - EPS: index.md
  - Documents: document.md
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 # Icon for light mode
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4 # Icon for dark mode
        name: Switch to light mode